colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = [ "news" ]
disableImageOptimization = true
disableTextInHeader = true
defaultBackgroundImage = "img/2018-06-23-10-55-13.jpg"
defaultFeaturedImage = "img/2018-06-23-10-55-13.jpg"
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false
showViews = false
showLikes = false

[header]
layout = "fixed"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = 6
showMoreLink = false
showMoreLinkDest = "news"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true
homepageImage = "img/2018-06-23-10-55-13.jpg"

[article]
showDate = true
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = false
showHero = true
heroStyle = "card"
layoutBackgroundBlur = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editURL = "https://github.com/langchr86/tsv-web"
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = false
showTableOfContents = true
showRelatedContent = false
relatedContentLimit = 6
showTaxonomies = true
showAuthorsBadges = false
showWordCount = false
sharingLinks = []
showZenMode = false

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showSummary = false
showTableOfContents = true
showCards = true
groupByYear = false
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showTableOfContents = true
cardView = false

[term]
showHero = true
heroStyle = "background"
showBreadcrumbs = false
showTableOfContents = false
groupByYear = false
cardView = true
cardViewScreenWidth = false

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[buymeacoffee]

[verification]
